version: '3.5'

services:
  update_firewall:
    container_name: update_firewall
    image: 'update_firewall/update_firewall:latest'
    restart: always
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      TZ: America/Los_Angeles
      LINODE_TOKEN: '${LINODE_TOKEN}'
      LINODE_FIREWALL_ID: '${LINODE_FIREWALL_ID}'
      LINODE_LABEL_NAME: '${LINODE_LABEL_NAME}'
      FROM_EMAIL: '${FROM_EMAIL}'
      TO_EMAIL: '${TO_EMAIL}'
      EMAIL_GREETING: '${EMAIL_GREETING}'
      SMTP_URL: '${SMTP_URL}'
      SMTP_PORT: '${SMTP_PORT}'
      SMTP_EMAIL: '${SMTP_EMAIL}'
      SMTP_PASSWORD: '${SMTP_PASSWORD}'
      PROXY_URL: '${PROXY_URL}'
